name: Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pip install poetry

      - name: Install depends
        run: poetry install --no-interaction

      - name: Lint with flake8
        run: flake8 --count

      - name: Run black
        run: black --check .

      - name: Run MyPy
        run: mypy --explicit-package-bases .

      - name: Run isort
        run: isort .

      - name: Run Pytest
        run: pytest -v .